[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rts-docs-dev"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
install = { cmd = ["pnpm", "install"] }
build = { cmd = ["pnpm", "build"], depends-on = ["install"] }
serve = { cmd = ["pnpm", "serve"], depends-on = ["build"] }

[dependencies]
nodejs = ">=22.9.0,<23"
pnpm = ">=9.11.0,<10"
