import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  genaiSidebar: [{type: 'autogenerated', dirName: 'genai'}],
  hpcSidebar: [{type: 'autogenerated', dirName: 'hpc'}],
  hsrnSidebar: [{type: 'autogenerated', dirName: 'hsrn'}],
  rtcSidebar: [{type: 'autogenerated', dirName: 'rtc'}],
  srdeSidebar: [{type: 'autogenerated', dirName: 'srde'}],
  
};

export default sidebars;
