# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - uses: actions/checkout@v4
      - run: npm i && npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
